version: 2.1
orbs:
  node: circleci/node@5.0.0

executors:
  linux-arm:
    machine:
      image: ubuntu-2004:202101-01

commands:
  install-npm:
    steps:
      - node/install:
          install-yarn: true
          node-version: "16.13.2"
          parameters:
            install-yarn:
              version: "1.22.5"
  
  install-dependencies:
    steps:
      - run:
          name: Install Dependencies
          command: yarn install --non-interactive --frozen-lockfile
  
  publish-electron-app:
    steps:
      - run:
          name: Publish
          command: yarn run publish
  
  yarn-make:
    steps:
      - run:
          name: Make Package
          command: yarn run make

  get-images:
    steps:
      - run:
          name: Get Images
          command: git clone https://$GITHUB_TOKEN@github.com/owlbear-rodeo/kenku-fm-assets.git
  
  move-images:
    steps:
      - run:
          name: Move Images to Directory
          command: | 
            mv ./kenku-fm-assets/backgrounds/*.jpg ./src/player/backgrounds
            rm -rf ./kenku-fm-assets

jobs:
  publish-electron-app-linux-arm:
    executor: linux-arm
    resource_class: arm.medium
    working_directory: ~/repo
    steps:
      - install-npm
      - run:
          name: Install dpkg and fakeroot
          command: |
            sudo apt-get update -y
            sudo apt-get install -y dpkg fakeroot rpm
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - install-dependencies
      - save_cache:
          key: dependency-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - get-images
      - move-images
      - publish-electron-app

workflows:
  version: 2
  deploy-linux-arm:
    jobs:
      - publish-electron-app-linux-arm:
          filters: &tag
            tags:
              only: 
                - /^v[0-9]+(\.[0-9]+)*-linux-arm$/
                - /^v[0-9]+(\.[0-9]+)*-([a-z]+)*-linux-arm$/
                - /^v[0-9]+(\.[0-9]+)*-([a-z]+)*[\.0-9]+-linux-arm$/
            branches:
              ignore: /.*/
